// Authentication
export const LOGIN_REQUEST = "LOGIN-REQUEST";
export const LOGIN_SUCCEEDED = "LOGIN-SUCCEEDED";
export const LOGIN_FAILED = "LOGIN-FAILED";

export const LOGOUT_REQUEST = "LOGOUT-REQUEST";
export const LOGOUT_SUCCEEDED = "LOGOUT-SUCCEEDED";

export const TOKEN_VERIFY_REQUEST = "TOKEN-VERIFY-REQUEST";
export const TOKEN_VERIFY_SUCCEDED = "TOKEN-VERIFY-SUCCEDED";
export const TOKEN_VERIFY_FAILED = "TOKEN-VERIFY-FAILED";

export const REFRESH_TOKEN_REQUEST = "REFRESH-TOKEN-REQUEST";
export const REFRESH_TOKEN_SUCCEDED = "REFRESH-TOKEN-SUCCEDED";
export const REFRESH_TOKEN_FAILED = "REFRESH-TOKEN-FAILED";

// Common
export const TOAST_REQUEST = "TOAST-REQUEST";
