export const LOGIN_REQUEST = "LOGIN-REQUEST";
export const LOGIN_SUCCEEDED = "LOGIN-SUCCEEDED";
export const LOGIN_FAILED = "LOGIN-FAILED";
export const LOGOUT_REQUEST = "LOGOUT-REQUEST";
export const LOGOUT_SUCCEEDED = "LOGOUT-SUCCEEDED";
